sudo: false
language: node_js
node_js:
  - "6.0"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm install -g angular-cli
  - npm install
  - ng build
after_success:
  - bash ./scripts/deploy.sh
