language: node_js
node_js:
  - "6"
before_install:
  - npm install -g angular-cli
  - npm install
  - ng build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: pages
