sudo: false
language: node_js
node_js:
  - "6.12.3"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm i -g npm@5.6.0
notifications:
  email: false
script:
  - npm install -g angular-cli
  - npm install
  - ng build --prod
after_success:
  - bash ./scripts/deploy.sh
